const realImagesBase = "/jamals/real";

export const restaurant = {
  name: "Jamal's Indian Restaurant",
  shortName: "Jamal's",
  established: "1956",
  tagline: "Indian Restaurant & Takeaway",
  heroLine: "Walton Street curry house. Order, collect, dine in.",
  description:
    "A long-standing Indian restaurant on Walton Street, Oxford, serving dine-in meals, collection, and local delivery.",
  phone: "01865 554905",
  secondaryPhone: "01865 512211",
  phoneHref: "tel:+441865554905",
  secondaryPhoneHref: "tel:+441865512211",
  email: "info@jamals-saffron.co.uk",
  bookingEmail: "bookings@jamals-saffron.co.uk",
  website: "jamals.orderdaily.uk",
  siteUrl: "https://jamals.orderdaily.uk",
  address: ["107-108 Walton Street", "Oxford", "OX2 6AJ"],
  location: "107-108 Walton Street, Oxford",
  deliveryInfo: "Delivery from \u00a320 in eligible Oxford postcodes",
  mapsUrl:
    "https://www.google.com/maps/search/?api=1&query=Jamal%27s%2C%20107-108%20Walton%20Street%2C%20Oxford%20OX2%206AJ",
  mapsEmbedUrl:
    "https://www.google.com/maps?q=Jamal%27s%2C%20107-108%20Walton%20Street%2C%20Oxford%20OX2%206AJ&output=embed",
  googleReviewsUrl:
    "https://www.google.com/search?q=jamals+oxford#lrd=0x4876c6a08325e861:0x682fcf341b511fe,1,,,,",
  hours: [
    { days: "Monday", time: "5.00pm - 11.00pm" },
    { days: "Tuesday", time: "Closed" },
    { days: "Wednesday & Thursday", time: "5.00pm - 11.00pm" },
    { days: "Friday & Saturday", time: "5.00pm - 11.30pm" },
    { days: "Sunday", time: "5.00pm - 11.00pm" },
  ],
};

export const navLinks = [
  { label: "Home", href: "/" },
  { label: "Menu", href: "/menu" },
  { label: "Gallery", href: "/gallery" },
  { label: "Booking", href: "/booking" },
  { label: "Track Order", href: "/track-order" },
  { label: "Reviews", href: "/reviews" },
  { label: "FAQs", href: "/faqs" },
  { label: "Contact", href: "/contact" },
];

export const foodImages = {
  hero: `${realImagesBase}/hero-restaurant.jpg`,
  curry: `${realImagesBase}/butter-chicken.jpg`,
  biryani: `${realImagesBase}/special-offers.jpg`,
  tandoori: `${realImagesBase}/tandoori-king-prawns.jpg`,
  naan: `${realImagesBase}/sides-bread.jpg`,
  rice: `${realImagesBase}/main-dishes.jpg`,
  restaurant: `${realImagesBase}/gallery-13.jpg`,
  exterior: `${realImagesBase}/gallery-14.jpg`,
  sign: `${realImagesBase}/gallery-15.jpg`,
  bar: `${realImagesBase}/gallery-11.jpg`,
  diningRoom: `${realImagesBase}/gallery-10.jpg`,
  starters: `${realImagesBase}/starters.jpg`,
  mainDishes: `${realImagesBase}/main-dishes.jpg`,
  vegetable: `${realImagesBase}/sides-bread.jpg`,
  sundries: `${realImagesBase}/booking-curry.jpg`,
  lambBalti: `${realImagesBase}/lamb-balti.jpg`,
  hygiene: `${realImagesBase}/food-hygiene-5.png`,
  halal: `${realImagesBase}/halal.png`,
};

const menuImagesBase = "/jamals/menu";

export const menuFoodImages = {
  balti: `${menuImagesBase}/balti-curry.jpg`,
  bhindiBhaji: `${menuImagesBase}/bhindi-bhaji.jpg`,
  biryani: `${menuImagesBase}/biryani.jpg`,
  bombayAloo: `${menuImagesBase}/bombay-aloo.jpg`,
  brinjalBhaji: `${menuImagesBase}/brinjal-bhaji.jpg`,
  butterChicken: `${menuImagesBase}/butter-chicken.jpg`,
  chanaMasala: `${menuImagesBase}/chana-masala.jpg`,
  chapati: `${menuImagesBase}/chapati.jpg`,
  cheeseNaan: `${menuImagesBase}/cheese-naan.jpg`,
  chickenTikka: `${menuImagesBase}/chicken-tikka.jpg`,
  chilliPaneer: `${menuImagesBase}/chilli-paneer.jpg`,
  chips: `${menuImagesBase}/chips.jpg`,
  eggFriedRice: `${menuImagesBase}/egg-fried-rice.jpg`,
  fishCurry: `${menuImagesBase}/fish-curry.jpg`,
  garlicChutney: `${menuImagesBase}/garlic-chutney.jpg`,
  garlicNaan: `${menuImagesBase}/garlic-naan.jpg`,
  hotpot: `${menuImagesBase}/hotpot-curry.jpg`,
  jalfrezi: `${menuImagesBase}/jalfrezi-curry.jpg`,
  keemaNaan: `${menuImagesBase}/keema-naan.jpg`,
  korma: `${menuImagesBase}/korma-curry.jpg`,
  limePickle: `${menuImagesBase}/lime-pickle.jpg`,
  mangoChutney: `${menuImagesBase}/mango-chutney.jpg`,
  masala: `${menuImagesBase}/masala-curry.jpg`,
  mintSauce: `${menuImagesBase}/mint-sauce.jpg`,
  mixedGrill: `${menuImagesBase}/mixed-grill.jpg`,
  mushroomBhaji: `${menuImagesBase}/mushroom-bhaji.jpg`,
  mushroomRice: `${menuImagesBase}/mushroom-rice.jpg`,
  naan: `${menuImagesBase}/naan.jpg`,
  onionBhaji: `${menuImagesBase}/onion-bhaji.jpg`,
  onionFriedRice: `${menuImagesBase}/onion-fried-rice.jpg`,
  onionSalad: `${menuImagesBase}/onion-salad.jpg`,
  paneerCurry: `${menuImagesBase}/paneer-curry.jpg`,
  paneerShashlik: `${menuImagesBase}/paneer-shashlik.jpg`,
  paratha: `${menuImagesBase}/paratha.jpg`,
  peshwariNaan: `${menuImagesBase}/peshwari-naan.jpg`,
  pilauRice: `${menuImagesBase}/pilau-rice.jpg`,
  plainRice: `${menuImagesBase}/plain-rice.jpg`,
  poppadom: `${menuImagesBase}/poppadom.jpg`,
  prawnCurry: `${menuImagesBase}/prawn-curry.jpg`,
  raita: `${menuImagesBase}/raita.jpg`,
  rogan: `${menuImagesBase}/rogan-curry.jpg`,
  saagAloo: `${menuImagesBase}/saag-aloo.jpg`,
  saagCurry: `${menuImagesBase}/saag-curry.jpg`,
  saagPaneer: `${menuImagesBase}/saag-paneer.jpg`,
  samosa: `${menuImagesBase}/samosa.jpg`,
  seekhKebab: `${menuImagesBase}/seekh-kebab.jpg`,
  setMeal: `${menuImagesBase}/set-meal.jpg`,
  tandooriChicken: `${menuImagesBase}/tandoori-chicken.jpg`,
  tarkaDal: `${menuImagesBase}/tarka-dal.jpg`,
  vegetableBiryani: `${menuImagesBase}/vegetable-biryani.jpg`,
  vindaloo: `${menuImagesBase}/vindaloo-curry.jpg`,
};

export const brandHeroImage = foodImages.hero;
export const logoImage = "/jamals/jamals-logo-optimized.png";

export const trustImages = {
  securePayments: "/jamals/trust/secure-payments.svg",
  foodHygieneRating: "/jamals/trust/food-hygiene-rating-5.svg",
};

export const aboutImages = [
  { src: foodImages.exterior, alt: "Jamal's restaurant exterior on Walton Street" },
  { src: foodImages.restaurant, alt: "Jamal's dining room set for service" },
  { src: foodImages.bar, alt: "Jamal's bar area" },
  { src: foodImages.hero, alt: "Jamal's curry and tandoori dishes" },
];

export const offers = [
  {
    title: "10% Collection Discount",
    detail: "Collection orders from \u00a320 qualify for 10% off.",
    note: "Collection only",
  },
  {
    title: "Free Onion Bhaji",
    detail: "Delivery orders over \u00a325 include a free Onion Bhaji.",
    note: "Delivery only",
  },
  {
    title: "Free Side Dish",
    detail: "Delivery orders over \u00a340 include your choice of side dish.",
    note: "Delivery only",
  },
  {
    title: "Free Onion Bhaji + Side Dish",
    detail: "Delivery orders over \u00a360 include a free Onion Bhaji plus your choice of side dish.",
    note: "Best delivery reward",
  },
];

export const studentOffer = {
  title: "Student Offer",
  price: "18",
  nonEaterPrice: "12",
  discount: "15%",
  capacity: "Up to 200 capacity",
  drinks: "Bring your own drinks",
  details: [
    "\u00a318 per head",
    "\u00a312 per head for non-eaters",
    "15% student discount",
    "Up to 200 capacity",
    "Bring your own drinks",
  ],
};

export const featuredDishes = [
  {
    name: "Butter Chicken",
    description: "Chicken fried in butter and served in a creamy sauce.",
    price: "12.50",
    badge: "Popular",
    image: foodImages.curry,
  },
  {
    name: "Tandoori King Prawns",
    description: "King prawns marinated with spices and cooked in the tandoor.",
    price: "16.50",
    badge: "Tandoori",
    image: foodImages.tandoori,
  },
  {
    name: "Lamb Balti",
    description: "Rich spices, onions and green peppers in a tangy curry sauce.",
    price: "12.95",
    badge: "Chef's Choice",
    image: foodImages.lambBalti,
  },
];

export const menuCategories = [
  { name: "Starters", count: "9", detail: "Tikka, samosa, bhaji, kebab and paneer" },
  { name: "Tandoori", count: "6", detail: "Shashlick, king prawns and mixed grill" },
  { name: "Chef Specialities", count: "31", detail: "Balti, Jalfrezi, Korai, Naga and Hotpot" },
  { name: "Traditional Mains", count: "40", detail: "Bhuna, Dansak, Korma, Madras and more" },
  { name: "Vegetable Dishes", count: "25", detail: "Aloo, saag, paneer, dall and bhaji dishes" },
  { name: "Rice & Bread", count: "14", detail: "Rice, naan, chapati, paratha and roti" },
];

type MenuItem = {
  name: string;
  price: string;
  description?: string;
  popular?: boolean;
};

type MenuSection = {
  id: string;
  title: string;
  description: string;
  image: string;
  items: MenuItem[];
  priceNote?: string;
};

export const menuSections: MenuSection[] = [
  {
    id: "poppadoms",
    title: "Poppadoms and Dips",
    description: "Crisp poppadoms and classic chutneys to start the table.",
    image: foodImages.starters,
    items: [
      { name: "Plain Poppadom", price: "0.85", description: "" },
      { name: "Spicy Poppadom", price: "0.85", description: "" },
      { name: "Mango Chutney", price: "0.95", description: "" },
      { name: "Onion Salad", price: "0.95", description: "" },
      { name: "Lime Pickle", price: "0.95", description: "" },
      { name: "Garlic Chutney", price: "0.95", description: "" },
      { name: "Mint Sauce", price: "0.95", description: "" },
    ],
  },
  {
    id: "starters",
    title: "Starters",
    description: "Tikka, samosas, bhaji, kebab, paneer and prawn puree.",
    image: foodImages.starters,
    items: [
      { name: "Meat Samosa", price: "6.25", description: "Filled triangular pastry. Contains gluten." },
      { name: "Vegetable Samosa", price: "5.25", description: "Filled triangular pastry. Contains gluten. Vegetarian." },
      { name: "Chicken Tikka", price: "6.95", description: "Tender pieces of boneless chicken marinated and cooked in the tandoor." },
      { name: "Lamb Tikka", price: "7.25", description: "Tender pieces of boneless lamb marinated and cooked in the tandoor." },
      { name: "Mixed Starter", price: "7.50", description: "Chicken tikka, seekh kebab, onion bhaji and vegetable samosa. Contains gluten." },
      { name: "Onion Bhaji", price: "5.25", description: "Vegetarian.", popular: true },
      { name: "Prawn Puree", price: "7.95", description: "Prawns cooked with spices and served on a fried Indian bread." },
      { name: "Sheek Kebab", price: "6.50", description: "Minced lamb skewered and chargrilled in the tandoor." },
      { name: "Chilli Paneer", price: "6.50", description: "Homemade cheese coated in cornflour, fried and sauteed with sweet chilli sauce. Contains gluten. Vegetarian." },
    ],
  },
  {
    id: "tandoori",
    title: "Tandoori Dishes",
    description: "Marinated in yoghurt, mixed herbs and ground spices, then roasted in the tandoor and served sizzling hot.",
    image: foodImages.tandoori,
    items: [
      { name: "Chicken Shashlick Main", price: "13.50", description: "Boneless chicken marinated in yoghurt, herbs and spices then roasted in the tandoor." },
      { name: "Lamb Shashlick Main", price: "14.50", description: "Boneless lamb marinated in yoghurt, herbs and spices then roasted in the tandoor." },
      { name: "Paneer Shashlick Main", price: "12.50", description: "Paneer marinated in yoghurt, herbs and spices then roasted in the tandoor. Vegetarian." },
      { name: "Tandoori Chicken Main (Half)", price: "12.50", description: "Chicken marinated in yoghurt with mixed herbs and ground spices, then roasted in the tandoor." },
      { name: "Tandoori King Prawns Main", price: "16.50", description: "King prawns marinated and cooked in the tandoor.", popular: true },
      { name: "Tandoori Mixed Grill Main", price: "16.50", description: "Tandoori chicken, lamb, chicken tikka and seekh kebabs roasted in the tandoor.", popular: true },
    ],
  },
  {
    id: "tandoori-massala",
    title: "Tandoori Massala Dishes",
    description: "Tandoori favourites cooked in a delicately marinated sauce with herbs and spices.",
    image: foodImages.curry,
    items: [
      { name: "Chicken Tikka Massala", price: "11.50", description: "Cooked in a delicately marinated sauce with herbs and spices.", popular: true },
      { name: "Lamb Tikka Massala", price: "13.25", description: "Cooked in a delicately marinated sauce with herbs and spices." },
      { name: "King Prawn Massala", price: "14.25", description: "Cooked in a delicately marinated sauce with herbs and spices." },
      { name: "Paneer Tikka Massala", price: "10.25", description: "Cooked in a delicately marinated sauce with herbs and spices." },
      { name: "Vegetable Massala", price: "9.50", description: "Cooked in a delicately marinated sauce with herbs and spices." },
    ],
  },
  {
    id: "chef-specialities",
    title: "Chef's Specialities",
    description: "Jamal's house specials, from Balti and Korai to Naga, Garlic Chilli and Hotpot.",
    image: foodImages.curry,
    items: [
      { name: "Chicken Balti", price: "11.50", description: "Stir fried rich spices, onions and green peppers in a tangy curry sauce. Medium hot." },
      { name: "Lamb Balti", price: "12.95", description: "Stir fried rich spices, onions and green peppers in a tangy curry sauce. Medium hot.", popular: true },
      { name: "Fish Balti", price: "12.95", description: "Stir fried rich spices, onions and green peppers in a tangy curry sauce. Medium hot." },
      { name: "Paneer Balti", price: "10.95", description: "Stir fried rich spices, onions and green peppers in a tangy curry sauce. Medium hot." },
      { name: "Chicken Jalfrezi", price: "11.50", description: "Fresh green chillies and assorted peppers. Hot.", popular: true },
      { name: "Lamb Jalfrezi", price: "12.95", description: "Fresh green chillies and assorted peppers. Hot." },
      { name: "Fish Jalfrezi", price: "12.95", description: "Fresh green chillies and assorted peppers. Hot." },
      { name: "Paneer Jalfrezi", price: "10.95", description: "Fresh green chillies and assorted peppers. Hot." },
      { name: "Chicken Kandahar", price: "11.50", description: "Afghani-style medium spice with tamarind, garlic, coriander and exotic spices." },
      { name: "Lamb Kandahar", price: "12.95", description: "Afghani-style medium spice with tamarind, garlic, coriander and exotic spices." },
      { name: "Fish Kandahar", price: "12.95", description: "Afghani-style medium spice with tamarind, garlic, coriander and exotic spices." },
      { name: "Paneer Kandahar", price: "10.95", description: "Afghani-style medium spice with tamarind, garlic, coriander and exotic spices." },
      { name: "Chicken Korai", price: "11.50", description: "Diced onions, green peppers, herbs and spices, served in a sizzling iron karahi pot." },
      { name: "Lamb Korai", price: "12.95", description: "Diced onions, green peppers, herbs and spices, served in a sizzling iron karahi pot." },
      { name: "Fish Korai", price: "12.95", description: "Diced onions, green peppers, herbs and spices, served in a sizzling iron karahi pot." },
      { name: "Paneer Korai", price: "10.95", description: "Diced onions, green peppers, herbs and spices, served in a sizzling iron karahi pot." },
      { name: "Chicken Passanda", price: "11.50", description: "Mild creamy sauce with coconut and red wine." },
      { name: "Lamb Passanda", price: "12.95", description: "Mild creamy sauce with coconut and red wine." },
      { name: "Ayer Jhol", price: "12.95", description: "Bangladeshi white fish curry, medium spiced." },
      { name: "Butter Chicken", price: "12.50", description: "Chicken fried in butter and served in a creamy sauce.", popular: true },
      { name: "Chicken Sagwala", price: "12.50", description: "Thinly sliced chicken breast with spinach, chilli and seeds in a creamy mild-spice sauce." },
      { name: "Garlic Chicken Paneer Jalfrezi", price: "12.95", description: "Marinated chicken tikka with fresh extra garlic, cheese, chilli and coriander. Hot.", popular: true },
      { name: "Jamal Indian Hotpot", price: "15.95", description: "Chicken, prawn and lamb cooked with onions and peppers, served in a special pot with an edible bread lid." },
      { name: "Chicken Naga", price: "11.50", description: "Fragrant, spicy Naga chilli. Very hot." },
      { name: "Lamb Naga", price: "12.95", description: "Fragrant, spicy Naga chilli. Very hot." },
      { name: "Fish Naga", price: "12.95", description: "Fragrant, spicy Naga chilli. Very hot." },
      { name: "Paneer Naga", price: "10.95", description: "Fragrant, spicy Naga chilli. Very hot." },
      { name: "Chicken Garlic Chilli", price: "11.50", description: "Rich thick garlicky sauce with fresh chillies. Hot." },
      { name: "Lamb Garlic Chilli", price: "12.95", description: "Rich thick garlicky sauce with fresh chillies. Hot." },
      { name: "Fish Garlic Chilli", price: "12.95", description: "Rich thick garlicky sauce with fresh chillies. Hot." },
      { name: "Paneer Garlic Chilli", price: "10.95", description: "Rich thick garlicky sauce with fresh chillies. Hot." },
    ],
  },
  {
    id: "traditional-main-dishes",
    title: "Traditional Main Dishes",
    description: "Classic curry styles with chicken, chicken tikka, lamb, king prawn or vegetable.",
    image: foodImages.mainDishes,
    items: [
      { name: "Chicken Bhuna", price: "10.50", description: "Cooked with tomatoes, green peppers and onions in a thick sauce." },
      { name: "Chicken Tikka Bhuna", price: "11.50", description: "Cooked with tomatoes, green peppers and onions in a thick sauce." },
      { name: "Lamb Bhuna", price: "11.25", description: "Cooked with tomatoes, green peppers and onions in a thick sauce." },
      { name: "King Prawn Bhuna", price: "13.50", description: "Cooked with tomatoes, green peppers and onions in a thick sauce." },
      { name: "Vegetable Bhuna", price: "9.95", description: "Cooked with tomatoes, green peppers and onions in a thick sauce." },
      { name: "Chicken Dansak", price: "10.50", description: "Sweet and sour, cooked with lentils, garlic and fenugreek. Hot." },
      { name: "Chicken Tikka Dansak", price: "11.50", description: "Sweet and sour, cooked with lentils, garlic and fenugreek. Hot." },
      { name: "Lamb Dansak", price: "11.25", description: "Sweet and sour, cooked with lentils, garlic and fenugreek. Hot." },
      { name: "King Prawn Dansak", price: "13.50", description: "Sweet and sour, cooked with lentils, garlic and fenugreek. Hot." },
      { name: "Vegetable Dansak", price: "9.95", description: "Sweet and sour, cooked with lentils, garlic and fenugreek. Hot." },
      { name: "Chicken Korma", price: "10.50", description: "Very mild dish cooked in almond and coconut sauce." },
      { name: "Chicken Tikka Korma", price: "11.50", description: "Very mild dish cooked in almond and coconut sauce." },
      { name: "Lamb Korma", price: "11.25", description: "Very mild dish cooked in almond and coconut sauce." },
      { name: "King Prawn Korma", price: "13.50", description: "Very mild dish cooked in almond and coconut sauce." },
      { name: "Vegetable Korma", price: "9.95", description: "Very mild dish cooked in almond and coconut sauce." },
      { name: "Chicken Madras", price: "10.50", description: "Popular rich and thick sauce. Hot." },
      { name: "Chicken Tikka Madras", price: "11.50", description: "Popular rich and thick sauce. Hot." },
      { name: "Lamb Madras", price: "11.25", description: "Popular rich and thick sauce. Hot." },
      { name: "King Prawn Madras", price: "13.50", description: "Popular rich and thick sauce. Hot." },
      { name: "Vegetable Madras", price: "9.95", description: "Popular rich and thick sauce. Hot." },
      { name: "Chicken Pathia", price: "10.50", description: "Hot, sweet and sour sauce with lime juice and coconut powder." },
      { name: "Chicken Tikka Pathia", price: "11.50", description: "Hot, sweet and sour sauce with lime juice and coconut powder." },
      { name: "Lamb Pathia", price: "11.25", description: "Hot, sweet and sour sauce with lime juice and coconut powder." },
      { name: "King Prawn Pathia", price: "13.50", description: "Hot, sweet and sour sauce with lime juice and coconut powder." },
      { name: "Vegetable Pathia", price: "9.95", description: "Hot, sweet and sour sauce with lime juice and coconut powder." },
      { name: "Chicken Rogan", price: "10.50", description: "North Indian dish with onions, tomatoes, green peppers and fresh herbs." },
      { name: "Chicken Tikka Rogan", price: "11.50", description: "North Indian dish with onions, tomatoes, green peppers and fresh herbs." },
      { name: "Lamb Rogan", price: "11.25", description: "North Indian dish with onions, tomatoes, green peppers and fresh herbs." },
      { name: "King Prawn Rogan", price: "13.50", description: "North Indian dish with onions, tomatoes, green peppers and fresh herbs." },
      { name: "Vegetable Rogan", price: "9.95", description: "North Indian dish with onions, tomatoes, green peppers and fresh herbs." },
      { name: "Chicken Sag", price: "10.50", description: "Spinach dish with onions, garlic and mixed spices." },
      { name: "Chicken Tikka Sag", price: "11.50", description: "Spinach dish with onions, garlic and mixed spices." },
      { name: "Lamb Sag", price: "11.25", description: "Spinach dish with onions, garlic and mixed spices." },
      { name: "King Prawn Sag", price: "13.50", description: "Spinach dish with onions, garlic and mixed spices." },
      { name: "Vegetable Sag", price: "9.95", description: "Spinach dish with onions, garlic and mixed spices." },
      { name: "Chicken Vindaloo", price: "10.50", description: "Popular rich and thick sauce. Very hot." },
      { name: "Chicken Tikka Vindaloo", price: "11.50", description: "Popular rich and thick sauce. Very hot." },
      { name: "Lamb Vindaloo", price: "11.25", description: "Popular rich and thick sauce. Very hot." },
      { name: "King Prawn Vindaloo", price: "13.50", description: "Popular rich and thick sauce. Very hot." },
      { name: "Vegetable Vindaloo", price: "9.95", description: "Popular rich and thick sauce. Very hot." },
    ],
  },
  {
    id: "biryani",
    title: "Biryani",
    description: "Basmati rice dishes mixed with spices, garnished and served with vegetable curry.",
    image: foodImages.biryani,
    items: [
      { name: "Chicken Biryani", price: "13.50", description: "" },
      { name: "Chicken Tikka Biryani", price: "14.50", description: "" },
      { name: "Lamb Biryani", price: "14.50", description: "" },
      { name: "King Prawn Biryani", price: "15.95", description: "" },
      { name: "Vegetable Biryani", price: "11.50", description: "Vegetarian." },
      { name: "Special Biryani", price: "15.50", description: "Chicken, lamb, prawns and omelette.", popular: true },
    ],
  },
  {
    id: "vegetable-dishes",
    title: "Vegetable Dishes",
    description: "Vegetarian sides and larger portions, including aloo, sag, paneer, dall and bhaji dishes.",
    image: foodImages.vegetable,
    items: [
      { name: "Bhindi Bhaji (Regular)", price: "6.75", description: "Okra." },
      { name: "Bhindi Bhaji (Large)", price: "8.25", description: "Okra." },
      { name: "Bombay Aloo (Regular)", price: "6.75", description: "Spiced potatoes." },
      { name: "Bombay Aloo (Large)", price: "8.25", description: "Spiced potatoes." },
      { name: "Brinjal Bhaji (Regular)", price: "6.75", description: "Aubergine." },
      { name: "Brinjal Bhaji (Large)", price: "8.25", description: "Aubergine." },
      { name: "Chana Dhansak (Regular)", price: "6.75", description: "Lentils and chickpeas in a thick sauce." },
      { name: "Chana Dhansak (Large)", price: "8.25", description: "Lentils and chickpeas in a thick sauce." },
      { name: "Chana Masala (Regular)", price: "6.75", description: "" },
      { name: "Chana Masala (Large)", price: "8.25", description: "" },
      { name: "Mottar Baigon (Regular)", price: "6.75", description: "Chickpeas and aubergine." },
      { name: "Mottar Baigon (Large)", price: "8.25", description: "Chickpeas and aubergine." },
      { name: "Chilli Paneer", price: "11.95", description: "Homemade cheese coated in cornflour, fried and sauteed with sweet chilli sauce." },
      { name: "Mushroom Bhaji (Regular)", price: "6.75", description: "Mushrooms." },
      { name: "Mushroom Bhaji (Large)", price: "8.25", description: "Mushrooms." },
      { name: "Sag Aloo (Regular)", price: "6.75", description: "Potatoes and spinach." },
      { name: "Sag Aloo (Large)", price: "8.25", description: "Potatoes and spinach." },
      { name: "Sag Bhaji (Regular)", price: "6.75", description: "Spinach." },
      { name: "Sag Bhaji (Large)", price: "8.25", description: "Spinach." },
      { name: "Sag Dall (Regular)", price: "6.75", description: "Spinach and lentils." },
      { name: "Sag Dall (Large)", price: "8.25", description: "Spinach and lentils." },
      { name: "Sag Paneer (Regular)", price: "6.95", description: "Spinach and cheese." },
      { name: "Sag Paneer (Large)", price: "8.95", description: "Spinach and cheese." },
      { name: "Tarka Dall (Regular)", price: "6.75", description: "Lentils." },
      { name: "Tarka Dall (Large)", price: "8.25", description: "Lentils." },
    ],
  },
  {
    id: "rice",
    title: "Rice",
    description: "Steamed, pilau, mushroom, egg, special and onion fried rice.",
    image: foodImages.rice,
    items: [
      { name: "Plain Rice", price: "2.95", description: "Steamed, vegetarian." },
      { name: "Pilau Rice", price: "3.25", description: "Basmati, vegetarian." },
      { name: "Mushroom Rice", price: "3.95", description: "Vegetarian, mushroom." },
      { name: "Egg Fried Rice", price: "3.95", description: "" },
      { name: "Special Rice", price: "3.95", description: "Vegetables and fried egg. Vegetarian." },
      { name: "Onion Fried Rice", price: "3.75", description: "" },
    ],
  },
  {
    id: "bread",
    title: "Bread",
    description: "Fresh tandoor breads, naan, chapati, paratha and roti.",
    image: foodImages.naan,
    items: [
      { name: "Plain Naan", price: "2.75", description: "Contains gluten." },
      { name: "Roshon Naan", price: "3.25", description: "Garlic naan. Contains gluten." },
      { name: "Cheese Naan", price: "3.95", description: "Contains gluten." },
      { name: "Peshwari Naan", price: "3.95", description: "Coconut. Contains gluten." },
      { name: "Keema Naan", price: "4.25", description: "Spiced minced meat. Contains gluten." },
      { name: "Chapati", price: "2.50", description: "Thin unleavened bread. Contains gluten." },
      { name: "Paratha", price: "3.25", description: "Plain. Contains gluten." },
      { name: "Tandoori Roti", price: "3.25", description: "Crispy bread. Contains gluten." },
    ],
  },
  {
    id: "set-meals",
    title: "Set Meals",
    description: "Chef-selected feasts priced per person.",
    image: foodImages.biryani,
    items: [
      { name: "Non Vegetarian Feast (per person)", price: "24.95", description: "Leave it to us feast. As selected by our expert chef.", popular: true },
      { name: "Vegetarian Feast (per person)", price: "22.95", description: "Leave it to us feast. As selected by our expert chef." },
    ],
  },
  {
    id: "sundries",
    title: "Sundries",
    description: "Raitha and chips to round out the order.",
    image: foodImages.sundries,
    items: [
      { name: "Cucumber Raitha", price: "2.25", description: "With yoghurt." },
      { name: "Onion Raitha", price: "2.25", description: "With yoghurt." },
      { name: "Chips", price: "2.95", description: "" },
    ],
  },
];

export type GalleryImageData = {
  alt: string;
  aspect: "landscape" | "portrait" | "square" | "wide";
  caption: string;
  category: "Signature" | "Tandoori" | "Curry" | "Restaurant" | "Drinks" | "Details";
  chapter: string;
  cta: string;
  featured?: boolean;
  href: string;
  mood: string;
  src: string;
  title: string;
};

export const galleryImages: GalleryImageData[] = [
  {
    title: "Butter Chicken",
    category: "Signature",
    chapter: "Signature dishes",
    caption: "Creamy curry, warm spice, and the dish people come back for.",
    src: foodImages.curry,
    alt: "Butter chicken curry served for dinner at Jamal's Indian Restaurant Oxford",
    mood: "House favourite",
    aspect: "wide",
    cta: "Order this tonight",
    href: "/menu#popular-picks",
    featured: true,
  },
  {
    title: "Tandoori King Prawns",
    category: "Tandoori",
    chapter: "From the tandoor",
    caption: "Smoky heat, charred edges, and seafood cooked with confidence.",
    src: foodImages.tandoori,
    alt: "Tandoori king prawns with Indian spices",
    mood: "Smoky tandoor",
    aspect: "portrait",
    cta: "Order tandoori",
    href: "/menu#tandoori-king-prawn",
    featured: true,
  },
  {
    title: "Special Biryani",
    category: "Signature",
    chapter: "Signature dishes",
    caption: "Fragrant rice layered for a generous curry-night centrepiece.",
    src: menuFoodImages.biryani,
    alt: "Special biryani rice dish with Indian spices",
    mood: "Fragrant rice",
    aspect: "square",
    cta: "See biryani",
    href: "/menu#biryani",
  },
  {
    title: "Lamb Balti",
    category: "Curry",
    chapter: "Curry comfort",
    caption: "Rich sauce, deep spice, and the comfort of a proper balti.",
    src: foodImages.lambBalti,
    alt: "Lamb balti curry served at Jamal's Indian Restaurant Oxford",
    mood: "Deep spice",
    aspect: "wide",
    cta: "Order curry",
    href: "/menu#traditional",
  },
  {
    title: "Paneer Shashlik",
    category: "Tandoori",
    chapter: "From the tandoor",
    caption: "Skewered paneer, peppers, and onions with bright tandoori colour.",
    src: menuFoodImages.paneerShashlik,
    alt: "Paneer shashlik skewers with peppers and onions",
    mood: "Vegetarian grill",
    aspect: "portrait",
    cta: "See tandoori",
    href: "/menu#tandoori-dishes",
  },
  {
    title: "Onion Bhaji",
    category: "Signature",
    chapter: "Start the table",
    caption: "Crisp, golden, and built for sharing before the mains arrive.",
    src: menuFoodImages.onionBhaji,
    alt: "Onion bhaji starter with chutneys",
    mood: "Crisp starter",
    aspect: "square",
    cta: "Add starters",
    href: "/menu#starters",
  },
  {
    title: "Garlic Naan",
    category: "Curry",
    chapter: "Curry comfort",
    caption: "Soft bread, charred bubbles, and the best way to finish the sauce.",
    src: menuFoodImages.garlicNaan,
    alt: "Garlic naan bread for Indian curry",
    mood: "Fresh bread",
    aspect: "landscape",
    cta: "Add sides",
    href: "/menu#rice-and-breads",
  },
  {
    title: "Restaurant Front",
    category: "Restaurant",
    chapter: "Walton Street",
    caption: "The familiar blue frontage on Walton Street, Oxford.",
    src: foodImages.exterior,
    alt: "Jamal's Indian Restaurant exterior on Walton Street Oxford",
    mood: "Oxford OX2",
    aspect: "portrait",
    cta: "Book a table",
    href: "/booking",
    featured: true,
  },
  {
    title: "Dining Room",
    category: "Restaurant",
    chapter: "Dining atmosphere",
    caption: "Comfortable tables for date nights, families, students, and groups.",
    src: foodImages.restaurant,
    alt: "Jamal's Indian Restaurant dining room in Oxford",
    mood: "Dinner setting",
    aspect: "wide",
    cta: "Reserve a table",
    href: "/booking",
  },
  {
    title: "Set Tables",
    category: "Restaurant",
    chapter: "Dining atmosphere",
    caption: "A warm room for relaxed BYOB dinners and curry-night plans.",
    src: foodImages.diningRoom,
    alt: "Dining tables set inside Jamal's Indian Restaurant",
    mood: "Table ready",
    aspect: "landscape",
    cta: "Reserve",
    href: "/booking",
  },
  {
    title: "Bar Area",
    category: "Drinks",
    chapter: "Drinks and details",
    caption: "The small details that make dinner feel like an evening out.",
    src: foodImages.bar,
    alt: "Jamal's restaurant bar area",
    mood: "Evening detail",
    aspect: "wide",
    cta: "Book tonight",
    href: "/booking",
  },
  {
    title: "Jamal's Sign",
    category: "Details",
    chapter: "Walton Street",
    caption: "Long-standing local presence, visible from Walton Street.",
    src: foodImages.sign,
    alt: "Jamal's restaurant sign in Oxford",
    mood: "Since 1956",
    aspect: "square",
    cta: "Get directions",
    href: restaurant.mapsUrl,
  },
  {
    title: "Tandoori Chicken",
    category: "Tandoori",
    chapter: "From the tandoor",
    caption: "Charred pieces from the tandoor with smoky spice and colour.",
    src: menuFoodImages.tandooriChicken,
    alt: "Tandoori chicken pieces with Indian spices",
    mood: "Chargrilled",
    aspect: "landscape",
    cta: "Order tandoori",
    href: "/menu#starters",
  },
  {
    title: "Saag Paneer",
    category: "Curry",
    chapter: "Vegetarian favourites",
    caption: "Green, comforting, and made for scooping with fresh bread.",
    src: menuFoodImages.saagPaneer,
    alt: "Saag paneer curry with Indian spices",
    mood: "Vegetarian comfort",
    aspect: "square",
    cta: "See sides",
    href: "/menu#vegetable-dishes",
  },
  {
    title: "Fresh Naan",
    category: "Curry",
    chapter: "Curry comfort",
    caption: "Soft bread for the table when the curry lands.",
    src: menuFoodImages.naan,
    alt: "Fresh naan bread served with curry",
    mood: "Table side",
    aspect: "portrait",
    cta: "Add bread",
    href: "/menu#rice-and-breads",
  },
  {
    title: "Food Hygiene Rating",
    category: "Details",
    chapter: "Trust signals",
    caption: "A clear trust signal before customers order or book.",
    src: foodImages.hygiene,
    alt: "Food hygiene rating 5 for Jamal's Indian Restaurant",
    mood: "Rated 5",
    aspect: "landscape",
    cta: "Order confidently",
    href: "/menu",
  },
  {
    title: "Halal",
    category: "Details",
    chapter: "Trust signals",
    caption: "Halal food available for guests and takeaway customers.",
    src: foodImages.halal,
    alt: "Halal food sign for Jamal's Indian Restaurant",
    mood: "Halal",
    aspect: "square",
    cta: "View menu",
    href: "/menu",
  },
];

export const reviews = [
  {
    name: "Anika Patel",
    title: "A real Oxford favourite",
    date: "2 days ago",
    helpful: 31,
    text: "The butter chicken and garlic naan were excellent. Warm service and real Oxford charm.",
  },
  {
    name: "James Wright",
    title: "Great collection offer",
    date: "1 week ago",
    helpful: 22,
    text: "Ordered for collection and the offer made it great value. Food was ready on time and full of flavour.",
  },
  {
    name: "Sara Ahmed",
    title: "Perfect student dinner",
    date: "2 weeks ago",
    helpful: 19,
    text: "The student deal is brilliant for groups. Bring your own drinks makes it even better.",
  },
  {
    name: "Oliver Green",
    title: "Best biryani nearby",
    date: "3 weeks ago",
    helpful: 16,
    text: "Special biryani was fragrant and generous. The side dishes were fresh and well spiced.",
  },
  {
    name: "Maya Khan",
    title: "Family meal done right",
    date: "1 month ago",
    helpful: 28,
    text: "We ordered the chef selected feast and everyone found something they loved.",
  },
  {
    name: "Daniel Brooks",
    title: "Reliable takeaway",
    date: "1 month ago",
    helpful: 17,
    text: "Easy ordering, helpful phone service, and consistently good curry.",
  },
];

export const faqs = [
  {
    category: "General",
    question: "What are Jamal's opening hours?",
    answer:
      "Jamal's opens Monday, Wednesday, Thursday and Sunday from 5.00pm to 11.00pm, and Friday and Saturday from 5.00pm to 11.30pm. Tuesday is closed.",
  },
  {
    category: "Ordering & Delivery",
    question: "What is the minimum delivery order?",
    answer: "The website accepts delivery orders from \u00a320 in eligible Oxford postcodes.",
  },
  {
    category: "Ordering & Delivery",
    question: "Do you offer collection discounts?",
    answer: "Yes. Collection orders from \u00a320 can receive 10% off.",
  },
  {
    category: "Ordering & Delivery",
    question: "What free delivery item offers are available?",
    answer:
      "Delivery orders over \u00a325 get a free Onion Bhaji, over \u00a340 get your choice of side dish, and over \u00a360 get both a free Onion Bhaji and your choice of side dish.",
  },
  {
    category: "Reservations",
    question: "What is the student offer?",
    answer:
      "Students can book from \u00a318 per head, with \u00a312 per head for non-eaters, 15% student discount, capacity up to 200, and bring your own drinks.",
  },
  {
    category: "Reservations",
    question: "Can customers book for large groups?",
    answer:
      "Yes. Jamal's can host student groups and larger gatherings, with capacity up to 200. Send your date, time, guest count, and notes from the booking page.",
  },
];
