const realImagesBase = "/jamals/real";

export const restaurant = {
  name: "Jamal's Indian Restaurant",
  shortName: "Jamal's",
  established: "1956",
  tagline: "Indian Restaurant & Takeaway",
  heroLine: "Walton Street curry house. Order, collect, dine in.",
  description:
    "A long-standing Indian restaurant on Walton Street, Oxford, serving dine-in meals, collection, and local delivery.",
  phone: "01865 554905",
  secondaryPhone: "01865 512211",
  phoneHref: "tel:+441865554905",
  secondaryPhoneHref: "tel:+441865512211",
  email: "info@jamals-saffron.co.uk",
  bookingEmail: "bookings@jamals-saffron.co.uk",
  website: "jamals.orderdaily.uk",
  siteUrl: "https://jamals.orderdaily.uk",
  address: ["107-108 Walton Street", "Oxford", "OX2 6AJ"],
  location: "107-108 Walton Street, Oxford",
  deliveryInfo: "Delivery from \u00a320 in eligible Oxford postcodes",
  mapsUrl:
    "https://www.google.com/maps/search/?api=1&query=Jamal%27s%2C%20107-108%20Walton%20Street%2C%20Oxford%20OX2%206AJ",
  mapsEmbedUrl:
    "https://www.google.com/maps?q=Jamal%27s%2C%20107-108%20Walton%20Street%2C%20Oxford%20OX2%206AJ&output=embed",
  googleReviewsUrl:
    "https://www.google.com/search?q=jamals+oxford#lrd=0x4876c6a08325e861:0x682fcf341b511fe,1,,,,",
  hours: [
    { days: "Monday", time: "5.00pm - 11.00pm" },
    { days: "Tuesday", time: "Closed" },
    { days: "Wednesday & Thursday", time: "5.00pm - 11.00pm" },
    { days: "Friday & Saturday", time: "5.00pm - 11.30pm" },
    { days: "Sunday", time: "5.00pm - 11.00pm" },
  ],
};

export const navLinks = [
  { label: "Home", href: "/" },
  { label: "Menu", href: "/menu" },
  { label: "Gallery", href: "/gallery" },
  { label: "Booking", href: "/booking" },
  { label: "Track Order", href: "/track-order" },
  { label: "Reviews", href: "/reviews" },
  { label: "FAQs", href: "/faqs" },
  { label: "Contact", href: "/contact" },
];

export const foodImages = {
  hero: `${realImagesBase}/hero-restaurant.jpg`,
  curry: `${realImagesBase}/butter-chicken.jpg`,
  biryani: `${realImagesBase}/special-offers.jpg`,
  tandoori: `${realImagesBase}/tandoori-king-prawns.jpg`,
  naan: `${realImagesBase}/sides-bread.jpg`,
  rice: `${realImagesBase}/main-dishes.jpg`,
  restaurant: `${realImagesBase}/gallery-13.jpg`,
  exterior: `${realImagesBase}/gallery-14.jpg`,
  sign: `${realImagesBase}/gallery-15.jpg`,
  bar: `${realImagesBase}/gallery-11.jpg`,
  diningRoom: `${realImagesBase}/gallery-10.jpg`,
  starters: `${realImagesBase}/starters.jpg`,
  mainDishes: `${realImagesBase}/main-dishes.jpg`,
  vegetable: `${realImagesBase}/sides-bread.jpg`,
  sundries: `${realImagesBase}/booking-curry.jpg`,
  lambBalti: `${realImagesBase}/lamb-balti.jpg`,
  hygiene: `${realImagesBase}/food-hygiene-5.png`,
  halal: `${realImagesBase}/halal.png`,
};

const menuImagesBase = "/jamals/menu";

export const menuFoodImages = {
  balti: `${menuImagesBase}/balti-curry.jpg`,
  bhindiBhaji: `${menuImagesBase}/bhindi-bhaji.jpg`,
  biryani: `${menuImagesBase}/biryani.jpg`,
  bombayAloo: `${menuImagesBase}/bombay-aloo.jpg`,
  brinjalBhaji: `${menuImagesBase}/brinjal-bhaji.jpg`,
  butterChicken: `${menuImagesBase}/butter-chicken.jpg`,
  chanaMasala: `${menuImagesBase}/chana-masala.jpg`,
  chapati: `${menuImagesBase}/chapati.jpg`,
  cheeseNaan: `${menuImagesBase}/cheese-naan.jpg`,
  chickenTikka: `${menuImagesBase}/chicken-tikka.jpg`,
  chilliPaneer: `${menuImagesBase}/chilli-paneer.jpg`,
  chips: `${menuImagesBase}/chips.jpg`,
  eggFriedRice: `${menuImagesBase}/egg-fried-rice.jpg`,
  fishCurry: `${menuImagesBase}/fish-curry.jpg`,
  garlicChutney: `${menuImagesBase}/garlic-chutney.jpg`,
  garlicNaan: `${menuImagesBase}/garlic-naan.jpg`,
  hotpot: `${menuImagesBase}/hotpot-curry.jpg`,
  jalfrezi: `${menuImagesBase}/jalfrezi-curry.jpg`,
  keemaNaan: `${menuImagesBase}/keema-naan.jpg`,
  korma: `${menuImagesBase}/korma-curry.jpg`,
  limePickle: `${menuImagesBase}/lime-pickle.jpg`,
  mangoChutney: `${menuImagesBase}/mango-chutney.jpg`,
  masala: `${menuImagesBase}/masala-curry.jpg`,
  mintSauce: `${menuImagesBase}/mint-sauce.jpg`,
  mixedGrill: `${menuImagesBase}/mixed-grill.jpg`,
  mushroomBhaji: `${menuImagesBase}/mushroom-bhaji.jpg`,
  mushroomRice: `${menuImagesBase}/mushroom-rice.jpg`,
  naan: `${menuImagesBase}/naan.jpg`,
  onionBhaji: `${menuImagesBase}/onion-bhaji.jpg`,
  onionFriedRice: `${menuImagesBase}/onion-fried-rice.jpg`,
  onionSalad: `${menuImagesBase}/onion-salad.jpg`,
  paneerCurry: `${menuImagesBase}/paneer-curry.jpg`,
  paneerShashlik: `${menuImagesBase}/paneer-shashlik.jpg`,
  paratha: `${menuImagesBase}/paratha.jpg`,
  peshwariNaan: `${menuImagesBase}/peshwari-naan.jpg`,
  pilauRice: `${menuImagesBase}/pilau-rice.jpg`,
  plainRice: `${menuImagesBase}/plain-rice.jpg`,
  poppadom: `${menuImagesBase}/poppadom.jpg`,
  prawnCurry: `${menuImagesBase}/prawn-curry.jpg`,
  raita: `${menuImagesBase}/raita.jpg`,
  rogan: `${menuImagesBase}/rogan-curry.jpg`,
  saagAloo: `${menuImagesBase}/saag-aloo.jpg`,
  saagCurry: `${menuImagesBase}/saag-curry.jpg`,
  saagPaneer: `${menuImagesBase}/saag-paneer.jpg`,
  samosa: `${menuImagesBase}/samosa.jpg`,
  seekhKebab: `${menuImagesBase}/seekh-kebab.jpg`,
  setMeal: `${menuImagesBase}/set-meal.jpg`,
  tandooriChicken: `${menuImagesBase}/tandoori-chicken.jpg`,
  tarkaDal: `${menuImagesBase}/tarka-dal.jpg`,
  vegetableBiryani: `${menuImagesBase}/vegetable-biryani.jpg`,
  vindaloo: `${menuImagesBase}/vindaloo-curry.jpg`,
};

export const brandHeroImage = foodImages.hero;
export const logoImage = "/jamals/jamals-logo-optimized.png";

export const trustImages = {
  securePayments: "/jamals/trust/secure-payments.svg",
  foodHygieneRating: "/jamals/trust/food-hygiene-rating-5.svg",
};

export const aboutImages = [
  { src: foodImages.exterior, alt: "Jamal's restaurant exterior on Walton Street" },
  { src: foodImages.restaurant, alt: "Jamal's dining room set for service" },
  { src: foodImages.bar, alt: "Jamal's bar area" },
  { src: foodImages.hero, alt: "Jamal's curry and tandoori dishes" },
];

export const offers = [
  {
    title: "10% Collection Discount",
    detail: "Collection orders from \u00a320 qualify for 10% off.",
    note: "Collection only",
  },
  {
    title: "Free Onion Bhaji",
    detail: "Delivery orders over \u00a330 include a free Onion Bhaji.",
    note: "Delivery only",
  },
  {
    title: "Free Side Dish",
    detail: "Delivery orders over \u00a345 include your choice of side dish.",
    note: "Delivery only",
  },
  {
    title: "Free Onion Bhaji + Side Dish",
    detail: "Delivery orders over \u00a360 include a free Onion Bhaji plus your choice of side dish.",
    note: "Best delivery reward",
  },
];

export const studentOffer = {
  title: "Student Offer",
  price: "18",
  nonEaterPrice: "12",
  discount: "15%",
  capacity: "Up to 200 capacity",
  drinks: "Bring your own drinks",
  details: [
    "\u00a318 per head",
    "\u00a312 per head for non-eaters",
    "15% student discount",
    "Up to 200 capacity",
    "Bring your own drinks",
  ],
};

export const featuredDishes = [
  {
    name: "Butter Chicken",
    description: "Chicken fried in butter and served in a creamy sauce.",
    price: "12.50",
    badge: "Popular",
    image: foodImages.curry,
  },
  {
    name: "Tandoori King Prawns",
    description: "King prawns marinated with spices and cooked in the tandoor.",
    price: "16.50",
    badge: "Tandoori",
    image: foodImages.tandoori,
  },
  {
    name: "Lamb Balti",
    description: "Rich spices, onions and green peppers in a tangy curry sauce.",
    price: "12.95",
    badge: "Chef's Choice",
    image: foodImages.lambBalti,
  },
];

export const menuCategories = [
  { name: "Starters", count: "9", detail: "Tikka, samosa, bhaji, kebab and paneer" },
  { name: "Tandoori", count: "6", detail: "Shashlick, king prawns and mixed grill" },
  { name: "Chef Specialities", count: "31", detail: "Balti, Jalfrezi, Korai, Naga and Hotpot" },
  { name: "Traditional Mains", count: "40", detail: "Bhuna, Dansak, Korma, Madras and more" },
  { name: "Vegetable Dishes", count: "25", detail: "Aloo, saag, paneer, dall and bhaji dishes" },
  { name: "Rice & Bread", count: "14", detail: "Rice, naan, chapati, paratha and roti" },
];

type MenuItem = {
  name: string;
  price: string;
  description?: string;
  popular?: boolean;
};

type MenuSection = {
  id: string;
  title: string;
  description: string;
  image: string;
  items: MenuItem[];
  priceNote?: string;
};

export const menuSections: MenuSection[] = [
  {
    id: "set-meal",
    title: "Set Meal",
    description: "Feasts priced per person as selected by our expert chef.",
    image: foodImages.biryani,
    items: [
      { name: "Feast Non Vegetarian", price: "24.95", description: "Per person as selected by our expert chef", popular: true },
      { name: "Feast Vegetarian", price: "22.95", description: "Per person as selected by our expert chef" },
    ],
  },
  {
    id: "vegetable-side-dishes",
    title: "Vegetable Side Dishes",
    description: "Vegetable side dishes, raitha, paneer and dhal.",
    image: foodImages.vegetable,
    items: [
      { name: "Chana Dansak", price: "6.75", description: "Lentils & chick peas in thick sauce" },
      { name: "Mottar Baigon", price: "6.75", description: "Chick peas & aubergine" },
      { name: "Tarka Dall", price: "6.75", description: "Lentils" },
      { name: "Brinjal Bhaji", price: "6.75", description: "Aubergine" },
      { name: "Bhindi Bhaji", price: "6.75", description: "Okra" },
      { name: "Sag Aloo", price: "6.75", description: "Potatoes & spinach" },
      { name: "Sag Dall", price: "6.75", description: "Spinach & lentils" },
      { name: "Bombay Aloo", price: "6.75", description: "Spiced potatoes" },
      { name: "Mushroom Bhaji", price: "6.75", description: "Mushrooms" },
      { name: "Sag Bhaji", price: "6.75", description: "Spinach" },
      { name: "Chana Masala", price: "6.75", description: "Chick peas" },
      { name: "Sag Paneer", price: "6.95", description: "Spinach & cheese" },
      { name: "Raitha", price: "2.25", description: "Yoghurt with cucumber / onion" },
    ],
  },
  {
    id: "vegetable-main-dishes",
    title: "Vegetable Main dishes",
    description: "Larger vegetable dishes, paneer and dhal.",
    image: foodImages.vegetable,
    items: [
      { name: "Chana Dhansak", price: "8.25", description: "Lentils & chick peas in thick sauce" },
      { name: "Mottar Baigon", price: "8.25", description: "Chick peas & aubergine" },
      { name: "Tarka Dall", price: "8.25", description: "Lentils" },
      { name: "Brinjal Bhaji", price: "8.25", description: "Aubergine" },
      { name: "Bhindi Bhaji", price: "8.25", description: "Okra" },
      { name: "Sag Aloo", price: "8.25", description: "Potatoes & spinach" },
      { name: "Sag Dall", price: "8.25", description: "Spinach & lentils" },
      { name: "Bombay Aloo", price: "8.25", description: "Spiced potatoes" },
      { name: "Mushroom Bhaji", price: "8.25", description: "Mushroom" },
      { name: "Sag Bhaji", price: "8.25", description: "Spinach" },
      { name: "Chana Masalla", price: "8.25", description: "Chick Pea" },
      { name: "Sag Paneer", price: "8.95", description: "Spinach & Cheese" },
      { name: "Chilli Paneer", price: "11.95", description: "Cubed pieces of homemade cheese, deep fried and sautéed with sweet chilli sauce." },
    ],
  },
  {
    id: "rice",
    title: "Rice",
    description: "Special, plain, pilau, mushroom, egg fried and onion fried rice.",
    image: foodImages.rice,
    items: [
      { name: "Special Rice", price: "3.95", description: "With vegetables & fried egg." },
      { name: "Plain Rice", price: "2.95", description: "Steamed" },
      { name: "Pilau Rice", price: "3.25", description: "Basmati" },
      { name: "Mushroom Rice", price: "3.95", description: "Mushroom" },
      { name: "Egg Fried Rice", price: "3.95", description: "" },
      { name: "Onion Fried Rice", price: "3.75", description: "" },
    ],
  },
  {
    id: "rotis",
    title: "Rotis",
    description: "Nan, roshon nan, paratha, tandoori roti, chapati and chips.",
    image: foodImages.naan,
    items: [
      { name: "Nan", price: "2.75", description: "" },
      { name: "Roshon Nan", price: "3.25", description: "Garlic" },
      { name: "Cheese Nan", price: "3.95", description: "Cheese" },
      { name: "Peshwari Nan", price: "3.95", description: "Coconut" },
      { name: "Keema Nan", price: "4.25", description: "Spice minced meat" },
      { name: "Paratha", price: "3.25", description: "Plain" },
      { name: "Tandoori Roti", price: "3.25", description: "Crispy bread" },
      { name: "Chapati", price: "2.50", description: "Thin unleavened bread" },
      { name: "Chips", price: "2.95", description: "" },
    ],
  },
  {
    id: "starters",
    title: "Starters",
    description: "Tikka, sheek kebab, samosas, bhaji, paneer, prawn puree, pappadum and chutney.",
    image: foodImages.starters,
    items: [
      { name: "Chicken Tikka", price: "6.95", description: "Tender pieces of boneless chicken, marinated and cooked in the tandoor.", popular: true },
      { name: "Lamb Tikka", price: "7.25", description: "Tender pieces of lamb, marinated and cooked in the tandoor." },
      { name: "Chicken Sheek Kebab", price: "6.50", description: "Minced chicken skewered & char-grilled in the tandoor." },
      { name: "Lamb Sheek Kebab", price: "6.50", description: "Minced lamb skewered & char-grilled in the tandoor." },
      { name: "Mix Starter", price: "7.50", description: "Chicken tikka, sheek kebab, onion bhaji & vegetable samosa." },
      { name: "Meat Samosas", price: "5.50", description: "Filled triangular pastry." },
      { name: "Vegetable Samosas", price: "5.50", description: "Filled triangular pastry." },
      { name: "Onion Bhaji", price: "5.25", description: "", popular: true },
      { name: "Chilli Paneer", price: "6.50", description: "Cubed pieces of homemade cheese, deep fried and sautéed with sweet chilli sauce." },
      { name: "Prawn Puree", price: "7.95", description: "Prawns cooked with spices & served on fried Indian bread." },
      { name: "Pappadum Spicy (each)", price: "0.85", description: "" },
      { name: "Pappadum Plain (each)", price: "0.85", description: "" },
      { name: "Mango Chutney (each)", price: "0.85", description: "" },
      { name: "Onion Salad (each)", price: "0.85", description: "" },
      { name: "Lime pickle (each)", price: "0.85", description: "" },
      { name: "Mint sauce (each)", price: "0.85", description: "" },
      { name: "Garlic chutney (each)", price: "0.85", description: "" },
    ],
  },
  {
    id: "tandoori",
    title: "Tandoori Dishes",
    description: "Marinated in yoghurt, mixed herbs and ground spices, then roasted in the tandoor and served sizzling hot.",
    image: foodImages.tandoori,
    items: [
      { name: "Chicken Shashlick", price: "13.50", description: "Chicken tikka" },
      { name: "Lamb Shashlick", price: "14.50", description: "Lamb tikka" },
      { name: "Tandoori Mixed Grill", price: "16.50", description: "Tandoori chicken, lamb tikka, chicken tikka with sheek kebabs.", popular: true },
      { name: "Tandoori Chicken (Half)", price: "12.50", description: "" },
      { name: "Tandoori King Prawns", price: "16.50", description: "", popular: true },
      { name: "Paneer Shashlick", price: "12.50", description: "" },
    ],
  },
  {
    id: "traditional-main-dishes",
    title: "Traditional Main Dishes",
    description: "Traditional curry styles with chicken, lamb, chicken tikka, king prawn or vegetable.",
    image: foodImages.mainDishes,
    items: [
      { name: "Bhuna Chicken", price: "10.50", description: "Cooked with tomatoes, green peppers & onions in thick sauce." },
      { name: "Bhuna Lamb", price: "11.25", description: "Cooked with tomatoes, green peppers & onions in thick sauce." },
      { name: "Bhuna Chicken Tikka", price: "11.50", description: "Cooked with tomatoes, green peppers & onions in thick sauce." },
      { name: "Bhuna King Prawn", price: "13.50", description: "Cooked with tomatoes, green peppers & onions in thick sauce." },
      { name: "Bhuna Vegetable", price: "9.95", description: "Cooked with tomatoes, green peppers & onions in thick sauce." },
      { name: "Sag Chicken", price: "10.50", description: "Spinach dish with onions, garlic & mixed spices." },
      { name: "Sag Lamb", price: "11.25", description: "Spinach dish with onions, garlic & mixed spices." },
      { name: "Sag Chicken Tikka", price: "11.50", description: "Spinach dish with onions, garlic & mixed spices." },
      { name: "Sag King Prawn", price: "13.50", description: "Spinach dish with onions, garlic & mixed spices." },
      { name: "Sag Vegetable", price: "9.95", description: "Spinach dish with onions, garlic & mixed spices." },
      { name: "Korma Chicken", price: "10.50", description: "Very mild dish cooked in a creamy coconut sauce." },
      { name: "Korma Lamb", price: "11.25", description: "Very mild dish cooked in a creamy coconut sauce." },
      { name: "Korma Chicken Tikka", price: "11.50", description: "Very mild dish cooked in a creamy coconut sauce." },
      { name: "Korma King Prawn", price: "13.50", description: "Very mild dish cooked in a creamy coconut sauce." },
      { name: "Korma Vegetable", price: "9.95", description: "Very mild dish cooked in a creamy coconut sauce." },
      { name: "Madras Chicken", price: "10.50", description: "Popular rich & thick sauce." },
      { name: "Madras Lamb", price: "11.25", description: "Popular rich & thick sauce." },
      { name: "Madras Chicken Tikka", price: "11.50", description: "Popular rich & thick sauce." },
      { name: "Madras King Prawn", price: "13.50", description: "Popular rich & thick sauce." },
      { name: "Madras Vegetable", price: "9.95", description: "Popular rich & thick sauce." },
      { name: "Methi Chicken", price: "10.50", description: "Fenegriek" },
      { name: "Methi Lamb", price: "11.25", description: "Fenegriek" },
      { name: "Methi Chicken Tikka", price: "11.50", description: "Fenegriek" },
      { name: "Methi King Prawn", price: "13.50", description: "Fenegriek" },
      { name: "Methi Vegetable", price: "9.95", description: "Fenegriek" },
      { name: "Dansak Chicken", price: "10.50", description: "Sweet & sour, cooked with lentils, garlic & fenugreek. Hot." },
      { name: "Dansak Lamb", price: "11.25", description: "Sweet & sour, cooked with lentils, garlic & fenugreek. Hot." },
      { name: "Dansak Chicken Tikka", price: "11.50", description: "Sweet & sour, cooked with lentils, garlic & fenugreek. Hot." },
      { name: "Dansak King Prawn", price: "13.50", description: "Sweet & sour, cooked with lentils, garlic & fenugreek. Hot." },
      { name: "Dansak Vegetable", price: "9.95", description: "Sweet & sour, cooked with lentils, garlic & fenugreek. Hot." },
      { name: "Pathia Chicken", price: "10.50", description: "Cooked in a hot, sweet sour sauce, lime juice & coconut." },
      { name: "Pathia Lamb", price: "11.25", description: "Cooked in a hot, sweet sour sauce, lime juice & coconut." },
      { name: "Pathia Chicken Tikka", price: "11.50", description: "Cooked in a hot, sweet sour sauce, lime juice & coconut." },
      { name: "Pathia King Prawn", price: "13.50", description: "Cooked in a hot, sweet sour sauce, lime juice & coconut." },
      { name: "Pathia Vegetable", price: "9.95", description: "Cooked in a hot, sweet sour sauce, lime juice & coconut." },
      { name: "Rogan Chicken", price: "10.50", description: "North Indian dish with onions, tomatoes, green peppers & fresh herbs." },
      { name: "Rogan Lamb", price: "11.25", description: "North Indian dish with onions, tomatoes, green peppers & fresh herbs." },
      { name: "Rogan Chicken Tikka", price: "11.50", description: "North Indian dish with onions, tomatoes, green peppers & fresh herbs." },
      { name: "Rogan King Prawn", price: "13.50", description: "North Indian dish with onions, tomatoes, green peppers & fresh herbs." },
      { name: "Rogan Vegetable", price: "9.95", description: "North Indian dish with onions, tomatoes, green peppers & fresh herbs." },
      { name: "Vindaloo Chicken", price: "10.50", description: "Popular rich & thick sauce." },
      { name: "Vindaloo Lamb", price: "11.25", description: "Popular rich & thick sauce." },
      { name: "Vindaloo Chicken Tikka", price: "11.50", description: "Popular rich & thick sauce." },
      { name: "Vindaloo King Prawn", price: "13.50", description: "Popular rich & thick sauce." },
      { name: "Vindaloo Vegetable", price: "9.95", description: "Popular rich & thick sauce." },
    ],
  },
  {
    id: "tandoori-massala",
    title: "Tandoori Massala Dishes",
    description: "Tandoori favourites cooked in a delicately marinated sauce with herbs & spice.",
    image: foodImages.curry,
    items: [
      { name: "Chicken Tikka Massala", price: "11.50", description: "Tandoori dishes cooked in a delicately marinated sauce with herbs & spice.", popular: true },
      { name: "Lamb Tikka Massala", price: "13.25", description: "Tandoori dishes cooked in a delicately marinated sauce with herbs & spice." },
      { name: "King Prawn Massala", price: "14.25", description: "Tandoori dishes cooked in a delicately marinated sauce with herbs & spice." },
      { name: "Vegetable Massala", price: "9.50", description: "Tandoori dishes cooked in a delicately marinated sauce with herbs & spice." },
      { name: "Paneer Tikka Massala", price: "10.25", description: "Tandoori dishes cooked in a delicately marinated sauce with herbs & spice." },
    ],
  },
  {
    id: "biryani",
    title: "Biryani",
    description: "Basmati rice dishes mixed with spices, garnished & served with vegetable curry.",
    image: foodImages.biryani,
    items: [
      { name: "Special Biryani", price: "15.50", description: "A traditional dish - mixed with basmati rice & spices, garnished & served with a vegetable curry. (Chicken, lamb, prawn & omelette)", popular: true },
      { name: "Vegetable Biryani", price: "11.50", description: "A traditional dish - mixed with basmati rice & spices, garnished & served with a vegetable curry." },
      { name: "Chicken Biryani", price: "13.50", description: "A traditional dish - mixed with basmati rice & spices, garnished & served with a vegetable curry." },
      { name: "Chicken Tikka Biryani", price: "14.50", description: "A traditional dish - mixed with basmati rice & spices, garnished & served with a vegetable curry." },
      { name: "Lamb Biryani", price: "14.50", description: "A traditional dish - mixed with basmati rice & spices, garnished & served with a vegetable curry." },
      { name: "King Prawn Biryani", price: "15.95", description: "A traditional dish - mixed with basmati rice & spices, garnished & served with a vegetable curry." },
    ],
  },
  {
    id: "chef-specialities",
    title: "Chef's Specialities",
    description: "Jamal's house specials, from balti and korai to naga, garlic chilli and hotpot.",
    image: foodImages.curry,
    items: [
      { name: "Garlic Chicken Paneer Jalfrezi", price: "12.95", description: "Marinated chicken tikka cooked with fresh extra garlic, cheese, chilli and coriander.", popular: true },
      { name: "Butter Chicken", price: "12.50", description: "Chicken fried in butter and served in a creamy sauce.", popular: true },
      { name: "Chicken Sagwala", price: "12.50", description: "Thinly sliced chicken breast with spinach & chilli seeds in creamy sauce." },
      { name: "Jamal Indian Hotpot", price: "15.95", description: "Chicken, prawn and lamb cooked with onions and peppers. Served in a special pot with an edible bread lid." },
      { name: "Ayer Jhol", price: "12.95", description: "Bangladeshi white fish curry, medium spiced." },
      { name: "Passanda Chicken", price: "12.50", description: "Cooked in a mild creamy sauce with coconut & red wine." },
      { name: "Passanda Lamb", price: "12.95", description: "Cooked in a mild creamy sauce with coconut & red wine." },
      { name: "Garlic Chilli Chicken", price: "11.50", description: "Rich thick garlicky sauce with fresh chillies." },
      { name: "Garlic Chilli Lamb", price: "12.95", description: "Rich thick garlicky sauce with fresh chillies." },
      { name: "Garlic Chilli Fish", price: "12.95", description: "Rich thick garlicky sauce with fresh chillies." },
      { name: "Garlic Chilli Paneer", price: "10.50", description: "Rich thick garlicky sauce with fresh chillies." },
      { name: "Naga Chicken", price: "11.50", description: "Exquisitely flavoured with fragrant and spicy Naga chilli, very hot." },
      { name: "Naga Lamb", price: "12.95", description: "Exquisitely flavoured with fragrant and spicy Naga chilli, very hot." },
      { name: "Naga Fish", price: "12.95", description: "Exquisitely flavoured with fragrant and spicy Naga chilli, very hot." },
      { name: "Naga Paneer", price: "10.50", description: "Exquisitely flavoured with fragrant and spicy Naga chilli, very hot." },
      { name: "Kandahar Chicken", price: "11.50", description: "An Afghanistani dish cooked with medium spice, tamarind, garlic, coriander & exotic spices." },
      { name: "Kandahar Lamb", price: "12.95", description: "An Afghanistani dish cooked with medium spice, tamarind, garlic, coriander & exotic spices." },
      { name: "Kandahar Fish", price: "12.95", description: "An Afghanistani dish cooked with medium spice, tamarind, garlic, coriander & exotic spices." },
      { name: "Kandahar Paneer", price: "10.50", description: "An Afghanistani dish cooked with medium spice, tamarind, garlic, coriander & exotic spices." },
      { name: "Balti Chicken", price: "11.50", description: "Stir-fried rich spices, onions & green peppers in a tangy curry sauce. Medium hot." },
      { name: "Balti Lamb", price: "12.95", description: "Stir-fried rich spices, onions & green peppers in a tangy curry sauce. Medium hot.", popular: true },
      { name: "Balti Fish", price: "12.95", description: "Stir-fried rich spices, onions & green peppers in a tangy curry sauce. Medium hot." },
      { name: "Balti Paneer", price: "10.50", description: "Stir-fried rich spices, onions & green peppers in a tangy curry sauce. Medium hot." },
      { name: "Korai Chicken", price: "11.50", description: "Prepared with diced onions, green peppers, herbs & spices. Served in sizzling iron Karahi pot." },
      { name: "Korai Lamb", price: "12.95", description: "Prepared with diced onions, green peppers, herbs & spices. Served in sizzling iron Karahi pot." },
      { name: "Korai Fish", price: "12.95", description: "Prepared with diced onions, green peppers, herbs & spices. Served in sizzling iron Karahi pot." },
      { name: "Korai Paneer", price: "10.50", description: "Prepared with diced onions, green peppers, herbs & spices. Served in sizzling iron Karahi pot." },
      { name: "Jalfrezi Chicken", price: "11.50", description: "With fresh green chillies and assortment of peppers, hot.", popular: true },
      { name: "Jalfrezi Lamb", price: "12.95", description: "With fresh green chillies and assortment of peppers, hot." },
      { name: "Jalfrezi Fish", price: "12.95", description: "With fresh green chillies and assortment of peppers, hot." },
      { name: "Jalfrezi Paneer", price: "10.50", description: "With fresh green chillies and assortment of peppers, hot." },
    ],
  },
];

export type GalleryImageData = {
  alt: string;
  aspect: "landscape" | "portrait" | "square" | "wide";
  caption: string;
  category: "Signature" | "Tandoori" | "Curry" | "Restaurant" | "Drinks" | "Details";
  chapter: string;
  cta: string;
  featured?: boolean;
  href: string;
  mood: string;
  src: string;
  title: string;
};

export const galleryImages: GalleryImageData[] = [
  {
    title: "Butter Chicken",
    category: "Signature",
    chapter: "Signature dishes",
    caption: "Creamy curry, warm spice, and the dish people come back for.",
    src: foodImages.curry,
    alt: "Butter chicken curry served for dinner at Jamal's Indian Restaurant Oxford",
    mood: "House favourite",
    aspect: "wide",
    cta: "Order this tonight",
    href: "/menu#popular-picks",
    featured: true,
  },
  {
    title: "Tandoori King Prawns",
    category: "Tandoori",
    chapter: "From the tandoor",
    caption: "Smoky heat, charred edges, and seafood cooked with confidence.",
    src: foodImages.tandoori,
    alt: "Tandoori king prawns with Indian spices",
    mood: "Smoky tandoor",
    aspect: "portrait",
    cta: "Order tandoori",
    href: "/menu#tandoori-king-prawn",
    featured: true,
  },
  {
    title: "Special Biryani",
    category: "Signature",
    chapter: "Signature dishes",
    caption: "Fragrant rice layered for a generous curry-night centrepiece.",
    src: menuFoodImages.biryani,
    alt: "Special biryani rice dish with Indian spices",
    mood: "Fragrant rice",
    aspect: "square",
    cta: "See biryani",
    href: "/menu#biryani",
  },
  {
    title: "Lamb Balti",
    category: "Curry",
    chapter: "Curry comfort",
    caption: "Rich sauce, deep spice, and the comfort of a proper balti.",
    src: foodImages.lambBalti,
    alt: "Lamb balti curry served at Jamal's Indian Restaurant Oxford",
    mood: "Deep spice",
    aspect: "wide",
    cta: "Order curry",
    href: "/menu#traditional",
  },
  {
    title: "Paneer Shashlik",
    category: "Tandoori",
    chapter: "From the tandoor",
    caption: "Skewered paneer, peppers, and onions with bright tandoori colour.",
    src: menuFoodImages.paneerShashlik,
    alt: "Paneer shashlik skewers with peppers and onions",
    mood: "Vegetarian grill",
    aspect: "portrait",
    cta: "See tandoori",
    href: "/menu#tandoori-dishes",
  },
  {
    title: "Onion Bhaji",
    category: "Signature",
    chapter: "Start the table",
    caption: "Crisp, golden, and built for sharing before the mains arrive.",
    src: menuFoodImages.onionBhaji,
    alt: "Onion bhaji starter with chutneys",
    mood: "Crisp starter",
    aspect: "square",
    cta: "Add starters",
    href: "/menu#starters",
  },
  {
    title: "Garlic Naan",
    category: "Curry",
    chapter: "Curry comfort",
    caption: "Soft bread, charred bubbles, and the best way to finish the sauce.",
    src: menuFoodImages.garlicNaan,
    alt: "Garlic naan bread for Indian curry",
    mood: "Fresh bread",
    aspect: "landscape",
    cta: "Add sides",
    href: "/menu#rice-and-breads",
  },
  {
    title: "Restaurant Front",
    category: "Restaurant",
    chapter: "Walton Street",
    caption: "The familiar blue frontage on Walton Street, Oxford.",
    src: foodImages.exterior,
    alt: "Jamal's Indian Restaurant exterior on Walton Street Oxford",
    mood: "Oxford OX2",
    aspect: "portrait",
    cta: "Book a table",
    href: "/booking",
    featured: true,
  },
  {
    title: "Dining Room",
    category: "Restaurant",
    chapter: "Dining atmosphere",
    caption: "Comfortable tables for date nights, families, students, and groups.",
    src: foodImages.restaurant,
    alt: "Jamal's Indian Restaurant dining room in Oxford",
    mood: "Dinner setting",
    aspect: "wide",
    cta: "Reserve a table",
    href: "/booking",
  },
  {
    title: "Set Tables",
    category: "Restaurant",
    chapter: "Dining atmosphere",
    caption: "A warm room for relaxed BYOB dinners and curry-night plans.",
    src: foodImages.diningRoom,
    alt: "Dining tables set inside Jamal's Indian Restaurant",
    mood: "Table ready",
    aspect: "landscape",
    cta: "Reserve",
    href: "/booking",
  },
  {
    title: "Bar Area",
    category: "Drinks",
    chapter: "Drinks and details",
    caption: "The small details that make dinner feel like an evening out.",
    src: foodImages.bar,
    alt: "Jamal's restaurant bar area",
    mood: "Evening detail",
    aspect: "wide",
    cta: "Book tonight",
    href: "/booking",
  },
  {
    title: "Jamal's Sign",
    category: "Details",
    chapter: "Walton Street",
    caption: "Long-standing local presence, visible from Walton Street.",
    src: foodImages.sign,
    alt: "Jamal's restaurant sign in Oxford",
    mood: "Since 1956",
    aspect: "square",
    cta: "Get directions",
    href: restaurant.mapsUrl,
  },
  {
    title: "Tandoori Chicken",
    category: "Tandoori",
    chapter: "From the tandoor",
    caption: "Charred pieces from the tandoor with smoky spice and colour.",
    src: menuFoodImages.tandooriChicken,
    alt: "Tandoori chicken pieces with Indian spices",
    mood: "Chargrilled",
    aspect: "landscape",
    cta: "Order tandoori",
    href: "/menu#starters",
  },
  {
    title: "Saag Paneer",
    category: "Curry",
    chapter: "Vegetarian favourites",
    caption: "Green, comforting, and made for scooping with fresh bread.",
    src: menuFoodImages.saagPaneer,
    alt: "Saag paneer curry with Indian spices",
    mood: "Vegetarian comfort",
    aspect: "square",
    cta: "See sides",
    href: "/menu#vegetable-dishes",
  },
  {
    title: "Fresh Naan",
    category: "Curry",
    chapter: "Curry comfort",
    caption: "Soft bread for the table when the curry lands.",
    src: menuFoodImages.naan,
    alt: "Fresh naan bread served with curry",
    mood: "Table side",
    aspect: "portrait",
    cta: "Add bread",
    href: "/menu#rice-and-breads",
  },
  {
    title: "Food Hygiene Rating",
    category: "Details",
    chapter: "Trust signals",
    caption: "A clear trust signal before customers order or book.",
    src: foodImages.hygiene,
    alt: "Food hygiene rating 5 for Jamal's Indian Restaurant",
    mood: "Rated 5",
    aspect: "landscape",
    cta: "Order confidently",
    href: "/menu",
  },
  {
    title: "Halal",
    category: "Details",
    chapter: "Trust signals",
    caption: "Halal food available for guests and takeaway customers.",
    src: foodImages.halal,
    alt: "Halal food sign for Jamal's Indian Restaurant",
    mood: "Halal",
    aspect: "square",
    cta: "View menu",
    href: "/menu",
  },
];

export const reviews = [
  {
    name: "Anika Patel",
    title: "A real Oxford favourite",
    date: "2 days ago",
    helpful: 31,
    text: "The butter chicken and garlic naan were excellent. Warm service and real Oxford charm.",
  },
  {
    name: "James Wright",
    title: "Great collection offer",
    date: "1 week ago",
    helpful: 22,
    text: "Ordered for collection and the offer made it great value. Food was ready on time and full of flavour.",
  },
  {
    name: "Sara Ahmed",
    title: "Perfect student dinner",
    date: "2 weeks ago",
    helpful: 19,
    text: "The student deal is brilliant for groups. Bring your own drinks makes it even better.",
  },
  {
    name: "Oliver Green",
    title: "Best biryani nearby",
    date: "3 weeks ago",
    helpful: 16,
    text: "Special biryani was fragrant and generous. The side dishes were fresh and well spiced.",
  },
  {
    name: "Maya Khan",
    title: "Family meal done right",
    date: "1 month ago",
    helpful: 28,
    text: "We ordered the chef selected feast and everyone found something they loved.",
  },
  {
    name: "Daniel Brooks",
    title: "Reliable takeaway",
    date: "1 month ago",
    helpful: 17,
    text: "Easy ordering, helpful phone service, and consistently good curry.",
  },
];

export const faqs = [
  {
    category: "General",
    question: "What are Jamal's opening hours?",
    answer:
      "Jamal's opens Monday, Wednesday, Thursday and Sunday from 5.00pm to 11.00pm, and Friday and Saturday from 5.00pm to 11.30pm. Tuesday is closed.",
  },
  {
    category: "Ordering & Delivery",
    question: "What is the minimum delivery order?",
    answer: "The website accepts delivery orders from \u00a320 in eligible Oxford postcodes.",
  },
  {
    category: "Ordering & Delivery",
    question: "Do you offer collection discounts?",
    answer: "Yes. Collection orders from \u00a320 can receive 10% off.",
  },
  {
    category: "Ordering & Delivery",
    question: "What free delivery item offers are available?",
    answer:
      "Delivery orders over \u00a330 get a free Onion Bhaji, over \u00a345 get your choice of side dish, and over \u00a360 get both a free Onion Bhaji and your choice of side dish.",
  },
  {
    category: "Reservations",
    question: "What is the student offer?",
    answer:
      "Students can book from \u00a318 per head, with \u00a312 per head for non-eaters, 15% student discount, capacity up to 200, and bring your own drinks.",
  },
  {
    category: "Reservations",
    question: "Can customers book for large groups?",
    answer:
      "Yes. Jamal's can host student groups and larger gatherings, with capacity up to 200. Send your date, time, guest count, and notes from the booking page.",
  },
];
